import { TemplateData } from "../_types";

export const TEMPLATES: TemplateData[] = [
  { emoji: "🔔", name: "Reengajar alunos inativos", description: "Email para alunos inativos há 7 dias", triggerType: "STUDENT_INACTIVE", triggerConfig: { inactiveDays: 7 }, actionType: "SEND_EMAIL", actionConfig: { subject: "Sentimos sua falta!", body: "Olá! Notamos que você não acessa há alguns dias.\n\nVolte e continue de onde parou!" }, needsCourse: false },
  { emoji: "👋", name: "Ativar quem nunca entrou", description: "Email para quem nunca acessou", triggerType: "STUDENT_NEVER_ACCESSED", triggerConfig: { afterDays: 3 }, actionType: "SEND_EMAIL", actionConfig: { subject: "Seu acesso está esperando!", body: "Olá! Você foi matriculado mas ainda não acessou.\n\nComece agora!" }, needsCourse: false },
  { emoji: "🔓", name: "Liberar módulo após conclusão", description: "Desbloqueia próximo módulo ao concluir", triggerType: "MODULE_COMPLETED", triggerConfig: {}, actionType: "UNLOCK_MODULE", actionConfig: {}, needsCourse: true },
  { emoji: "📧", name: "Email de parabéns no quiz", description: "Parabéns quando passa no quiz", triggerType: "QUIZ_PASSED", triggerConfig: {}, actionType: "SEND_EMAIL", actionConfig: { subject: "Parabéns! Você passou no quiz!", body: "Excelente resultado! Continue avançando." }, needsCourse: true },
  { emoji: "📊", name: "Alertar baixo progresso", description: "Email para quem está abaixo de 25%", triggerType: "PROGRESS_BELOW", triggerConfig: { progressPercent: 25, afterDays: 14 }, actionType: "SEND_EMAIL", actionConfig: { subject: "Precisa de ajuda?", body: "Vimos que você está no início. Estamos aqui para ajudar!" }, needsCourse: true },
  { emoji: "🎉", name: "Parabenizar 50% de progresso", description: "Comemora ao atingir metade do curso", triggerType: "PROGRESS_ABOVE", triggerConfig: { progressPercent: 50 }, actionType: "SEND_EMAIL", actionConfig: { subject: "Você já está na metade!", body: "Parabéns! Continue assim!" }, needsCourse: true },
  { emoji: "📚", name: "Matricular em curso bônus", description: "Matricula em outro curso ao concluir", triggerType: "COURSE_COMPLETED", triggerConfig: {}, actionType: "ENROLL_COURSE", actionConfig: {}, needsCourse: true },
  { emoji: "🏷️", name: "Ação em massa por tag", description: "Envie email para todos os alunos com uma tag", triggerType: "HAS_TAG", triggerConfig: {}, actionType: "SEND_EMAIL", actionConfig: { subject: "Mensagem importante", body: "Olá! Temos uma novidade para você." }, needsCourse: false },
  { emoji: "🔔", name: "Push de conteúdo novo", description: "Notificação push ao se matricular", triggerType: "STUDENT_ENROLLED", triggerConfig: {}, actionType: "SEND_PUSH", actionConfig: { pushTitle: "Novidade no {curso}!", pushBody: "Olá {nome}, tem conteúdo novo te esperando!", pushUrl: "/" }, needsCourse: true },
  { emoji: "📲", name: "Reengajar via push", description: "Push para alunos inativos há 7 dias", triggerType: "STUDENT_INACTIVE", triggerConfig: { inactiveDays: 7 }, actionType: "SEND_PUSH", actionConfig: { pushTitle: "Sentimos sua falta, {nome}!", pushBody: "Faz dias que você não aparece. Volte e continue de onde parou!", pushUrl: "/" }, needsCourse: false },
];
